global:
  clusterId: "mahmud-gke-cluster"
  federatedStorage:
    enabled: true  # Turn this to true so it looks for the secret
    existingSecret: "kubecost-federated-store" # Points to the dummy secret

kubecostProductConfigs:
  clusterName: "mahmud-gke-cluster"

prometheus:
  server:
    global:
      external_labels:
        cluster_id: "mahmud-gke-cluster"